services:
  db:
    image: mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./barber_data:/var/lib/mysql
    ports:
      - 3306:3306
  
  php:
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    build: 
      context: .
      dockerfile: ./config/php/Dockerfile
    volumes:
      - ./:/var/www
    expose:
      - 9000
  server:
    container_name: "${COMPOSE_PROJECT_NAME}_server"
    image: nginx:mainline-alpine
    volumes:
       - ./:/var/www:ro
       - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
       - NGINX_HOST=mylocal.com
       - NGINX_PORT=80
    ports:
       - 8000:80

volumes:
  barber_data:
